In [1]:
# Import the dependencies.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 1 hours),Snow inches (last 1 hours)
0,0,Penzance,GB,2020-07-12 16:38:01,50.12,-5.54,66.99,59,41,9.17,scattered clouds,0.0,0
1,1,Hobart,AU,2020-07-12 16:37:59,-42.88,147.33,39.00,93,90,10.29,overcast clouds,0.0,0
2,2,Busselton,AU,2020-07-12 16:38:21,-33.65,115.33,57.00,80,49,15.30,scattered clouds,0.0,0
3,3,Severo-Kurilsk,RU,2020-07-12 16:38:22,50.68,156.12,49.50,92,100,10.09,overcast clouds,0.0,0
4,4,Saint George,US,2020-07-12 16:36:14,37.10,-113.58,93.99,21,1,4.70,clear sky,0.0,0

In [3]:
# Prompt the customer for the minimum temperature preference.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
# Prompt the customer for the maximum temperature preference. 
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
# Prompt the customer to answer if he or she would like it to be raining or not.
rain = str(input('Do you want it to be raining? (yes/no)\n'))
# Prompt the customer to answer if he or she would like it to be snowing or not
snow = str(input('Do you want it to be snowing? (yes/no)\n'))

What is the minimum temperature you would like for your trip? 50
What is the maximum temperature you would like for your trip? 90
Do you want it to be raining? (yes/no)
yes
Do you want it to be snowing? (yes/no)
no

In [4]:
# Filter the dataset to find the cities that fit the criteria.
for index, row in city_data_df.iterrows():
    if rain == "no":
        rain_inches = city_data_df["Rain inches (last 1 hours)"] == 0
    else:
        rain_inches = city_data_df["Rain inches (last 1 hours)"] != 0
    if snow == "no":
        snow_inches = city_data_df["Snow inches (last 1 hours)"] == 0
    else:
        snow_inches = city_data_df["Snow inches (last 1 hours)"] != 0

In [5]:
# Filter the dataset to find the cities that fit the criteria.

preferred_cities_df = city_data_df.loc[(city_data_df["Rain inches (last 1 hours)"] != rain_inches) &
                                       (city_data_df["Snow inches (last 1 hours)"] != snow_inches) &
                                       (city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
                                       
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 1 hours),Snow inches (last 1 hours)
10,10,Dicabisagan,PH,2020-07-12 16:38:22,17.08,122.42,79.74,82,100,3.58,light rain,0.37,0
12,12,Sholokhovskiy,RU,2020-07-12 16:38:22,48.28,41.05,76.08,63,20,17.38,light rain,0.19,0
43,43,Amahai,ID,2020-07-12 16:38:26,-3.33,128.92,77.29,88,99,5.14,light rain,0.38,0
66,66,Baoro,CF,2020-07-12 16:38:29,5.67,15.97,73.76,87,57,2.93,light rain,0.29,0
71,71,Zhob,PK,2020-07-12 16:38:30,31.34,69.45,75.76,50,20,8.57,moderate rain,1.11,0
78,78,Saint-Philippe,RE,2020-07-12 16:38:31,-21.36,55.77,69.80,82,52,3.36,light rain,0.33,0
85,85,Coari,BR,2020-07-12 16:38:32,-4.08,-63.14,84.16,75,76,2.59,light rain,0.60,0
86,86,Marawi,PH,2020-07-12 16:38:32,8.00,124.29,75.99,87,99,7.00,light rain,0.63,0
89,89,Kiunga,PG,2020-07-12 16:38:33,-6.12,141.29,72.45,98,87,0.69,moderate rain,1.93,0
99,99,Vanimo,PG,2020-07-12 16:38:34,-2.67,141.30,78.46,80,99,0.96,light rain,0.41,0

In [6]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
10,Dicabisagan,PH,79.74,light rain,17.08,122.42,
12,Sholokhovskiy,RU,76.08,light rain,48.28,41.05,
43,Amahai,ID,77.29,light rain,-3.33,128.92,
66,Baoro,CF,73.76,light rain,5.67,15.97,
71,Zhob,PK,75.76,moderate rain,31.34,69.45,
78,Saint-Philippe,RE,69.80,light rain,-21.36,55.77,
85,Coari,BR,84.16,light rain,-4.08,-63.14,
86,Marawi,PH,75.99,light rain,8.00,124.29,
89,Kiunga,PG,72.45,moderate rain,-6.12,141.29,
99,Vanimo,PG,78.46,light rain,-2.67,141.30,

In [7]:
# Dependencies and Setup
import requests
import gmaps


# Import API key
from config import g_key

In [8]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to the params dictionary as values to the location key.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()

In [9]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [10]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 1 hours),Snow inches (last 1 hours)
10,10,Dicabisagan,PH,2020-07-12 16:38:22,17.08,122.42,79.74,82,100,3.58,light rain,0.37,0
12,12,Sholokhovskiy,RU,2020-07-12 16:38:22,48.28,41.05,76.08,63,20,17.38,light rain,0.19,0
43,43,Amahai,ID,2020-07-12 16:38:26,-3.33,128.92,77.29,88,99,5.14,light rain,0.38,0
66,66,Baoro,CF,2020-07-12 16:38:29,5.67,15.97,73.76,87,57,2.93,light rain,0.29,0
71,71,Zhob,PK,2020-07-12 16:38:30,31.34,69.45,75.76,50,20,8.57,moderate rain,1.11,0
78,78,Saint-Philippe,RE,2020-07-12 16:38:31,-21.36,55.77,69.80,82,52,3.36,light rain,0.33,0
85,85,Coari,BR,2020-07-12 16:38:32,-4.08,-63.14,84.16,75,76,2.59,light rain,0.60,0
86,86,Marawi,PH,2020-07-12 16:38:32,8.00,124.29,75.99,87,99,7.00,light rain,0.63,0
89,89,Kiunga,PG,2020-07-12 16:38:33,-6.12,141.29,72.45,98,87,0.69,moderate rain,1.93,0
99,99,Vanimo,PG,2020-07-12 16:38:34,-2.67,141.30,78.46,80,99,0.96,light rain,0.41,0

In [12]:
Baoro = preferred_cities_df[preferred_cities_df['City'].str.contains("Baoro")]
Baoro

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 1 hours),Snow inches (last 1 hours)
66,66,Baoro,CF,2020-07-12 16:38:29,5.67,15.97,73.76,87,57,2.93,light rain,0.29,0

In [13]:
Zhob = preferred_cities_df[preferred_cities_df['City'].str.contains("Zhob")]
Zhob

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 1 hours),Snow inches (last 1 hours)
71,71,Zhob,PK,2020-07-12 16:38:30,31.34,69.45,75.76,50,20,8.57,moderate rain,1.11,0

In [14]:
Marawi = preferred_cities_df[preferred_cities_df['City'].str.contains("Marawi")]
Marawi

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 1 hours),Snow inches (last 1 hours)
86,86,Marawi,PH,2020-07-12 16:38:32,8.0,124.29,75.99,87,99,7.0,light rain,0.63,0

In [15]:
Vanimo = preferred_cities_df[preferred_cities_df['City'].str.contains("Vanimo")]
Vanimo

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 1 hours),Snow inches (last 1 hours)
99,99,Vanimo,PG,2020-07-12 16:38:34,-2.67,141.3,78.46,80,99,0.96,light rain,0.41,0

In [16]:
four_cities = pd.concat([Baoro,Zhob,Marawi,Vanimo])
four_cities

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 1 hours),Snow inches (last 1 hours)
66,66,Baoro,CF,2020-07-12 16:38:29,5.67,15.97,73.76,87,57,2.93,light rain,0.29,0
71,71,Zhob,PK,2020-07-12 16:38:30,31.34,69.45,75.76,50,20,8.57,moderate rain,1.11,0
86,86,Marawi,PH,2020-07-12 16:38:32,8.00,124.29,75.99,87,99,7.00,light rain,0.63,0
99,99,Vanimo,PG,2020-07-12 16:38:34,-2.67,141.30,78.46,80,99,0.96,light rain,0.41,0

In [17]:
columnsData = four_cities.loc[:,['City','Lat','Lng']]
columnsData

      City    Lat     Lng
66   Baoro   5.67   15.97
71    Zhob  31.34   69.45
86  Marawi   8.00  124.29
99  Vanimo  -2.67  141.30

In [27]:
import gmaps
import gmaps.datasets
gmaps.configure(api_key= "g_key")

# Latitude-longitude pairs
Baoro= (5.67, 15.97)
Zhob = (31.34, 69.45)
Marawi = (8.00, 124.29)
Vanimo = (-2.67, 141.30)

fig = gmaps.figure()
Pic = gmaps.directions_layer(Baoro, Zhob , waypoints=[Marawi, Vanimo])
fig.add_layer(Pic)
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
fig = gmaps.figure()
Pic_via_driving = gmaps.directions_layer(
        Baoro, Zhob, waypoints=[Marawi, Vanimo],  
        travel_mode='DRIVING')
fig.add_layer(Pic_via_driving)
fig

Figure(layout=FigureLayout(height='420px'))

In [20]:
four_cities

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 1 hours),Snow inches (last 1 hours)
66,66,Baoro,CF,2020-07-12 16:38:29,5.67,15.97,73.76,87,57,2.93,light rain,0.29,0
71,71,Zhob,PK,2020-07-12 16:38:30,31.34,69.45,75.76,50,20,8.57,moderate rain,1.11,0
86,86,Marawi,PH,2020-07-12 16:38:32,8.00,124.29,75.99,87,99,7.00,light rain,0.63,0
99,99,Vanimo,PG,2020-07-12 16:38:34,-2.67,141.30,78.46,80,99,0.96,light rain,0.41,0

In [21]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
# Iterate through the DataFrame.
for index, row in four_cities.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to the params dictionary as values to the location key.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()

In [25]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
four_cities_hotel_info = [info_box_template.format(**row) for index, row in four_cities.iterrows()]

KeyError: 'Hotel Name'

In [26]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = four_cities[["Lat", "Lng"]]
max_temp = four_cities["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=four_cities_hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

NameError: name 'four_cities_hotel_info' is not defined